zeebe:
  client:
    broker:
      gateway-address: localhost:26500
    security:
      plaintext: true
    cloud:
      client-id: connectors
      client-secret: XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
      auth-url: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
